{% set name = "waves" %}
{% set version = "0.6.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lanl/waves/archive/refs/tags/{{ version }}.tar.gz
  sha256: d646f72317f7f587cf3759043bf2aa1f9c2b18ef3b94eae29f022069d33066e7

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - {{ PYTHON }} setup.py install
    - scons man html
    - {{ PYTHON }} package_documentation.py
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - scons >=4
    - setuptools >=45
    - setuptools_scm[toml] >=6.2
    - sphinx >=5.1
    - sphinx-argparse
    - sphinx_rtd_theme >=1
    - sphinxcontrib-bibtex
  host:
    - python
    - setuptools >=45
    - setuptools_scm[toml] >=6.2
  run:
    - python >=3.8
    - h5netcdf
    - h5py
    - matplotlib
    - networkx
    - numpy
    - pyyaml
    - salib >=1
    - scipy >=1.7
    - scons
    - xarray

test:
  requires:
    - pytest
    - pytest-xdist
  imports:
    - waves

about:
  home: https://github.com/lanl/waves
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Parameteric study computational engineering workflow tool
  description: |
    WAVES (LANL code C23004) is a computational engineering workflow tool that integrates parametric studies with
    traditional software build systems.
  doc_url: https://lanl.github.io/waves/index.html
  dev_url: https://github.com/lanl/waves

extra:
  recipe-maintainers:
    - Prabhu-LANL
    - kbrindley
